### ISSUE TITLE
Error: The value of property "content" is longer than 1500 bytes.

### ISSUE THREAD

**Issue by trmazurkevych** [fabito/botkit-storage-datastore#14]
Getting the error `{ Error: 3 INVALID_ARGUMENT: The value of property "content" is longer than 1500 bytes.`
Most probably it's caused by my code.
But to confirm, is there a chance it's caused by botkit-storage-datastore?

**Comment by fabito** [comment]
Probably not.
Most likely your entity has a property `content` which is longer than 1500 bytes and is not excluded from the index.
You should try try to exclude it with:

```
      {
        name: 'content',
        value: Something longer than 1500 bytes,
        excludeFromIndexes: true,
      }
```

**Comment by trmazurkevych** [comment]
Thanks
